### ISSUE TITLE
With extra translation bundle loaded, got File not found: manuals\$rtfm.docs.title\$rtfm.docs.getting-started

### ISSUE THREAD

**Issue by liuxilu** [DeltaNedas/rtfm#14]
I tried to install from `Import From Github` and manually download from github.
Is it a Mindustry bug?
```
[I] [JAVA] Version: 1.8.0_221
[I] NOTE: external translation bundle has been loaded.
[I] Loaded mod 'rtfm' in 18.7664ms
[E] rhino.WrappedException: Wrapped arc.util.ArcRuntimeException: File not found: manuals\$rtfm.docs.title\$rtfm.docs.getting-started (internal) (global.js#8)
        at rhino.Context.throwAsScriptRuntimeEx(Context.java:1668)
        at rhino.MemberBox.invoke(MemberBox.java:127)
        at rhino.NativeJavaMethod.call(NativeJavaMethod.java:205)
        at rhino.optimizer.OptRuntime.call1(OptRuntime.java:23)
        at rhino.gen.global_js_1._c_anonymous_2(global.js:8)
        at rhino.gen.global_js_1.call(global.js)
        at rhino.ArrowFunction.call(ArrowFunction.java:33)
        at rhino.optimizer.OptRuntime.callName(OptRuntime.java:51)
        at rhino.gen.library_4._c_anonymous_2(library:31)
        at rhino.gen.library_4.call(library)
        at rhino.ArrowFunction.call(ArrowFunction.java:33)
        at rhino.optimizer.OptRuntime.callName(OptRuntime.java:51)
        at rhino.gen.library_4._c_anonymous_7(library:78)
        at rhino.gen.library_4.call(library)
        at rhino.optimizer.OptRuntime.callN(OptRuntime.java:41)
        at rhino.gen.library_4._c_anonymous_9(library:135)
        at rhino.gen.library_4.call(library)
        at rhino.optimizer.OptRuntime.call2(OptRuntime.java:32)
        at rhino.gen.docs_7._c_script_0(docs:21)
        at rhino.gen.docs_7.call(docs)
        at rhino.gen.docs_7.exec(docs)
        at rhino.module.Require.executeModuleScript(Require.java:321)
        at rhino.module.Require.getExportedModuleInterface(Require.java:272)
        at rhino.module.Require.call(Require.java:202)
        at rhino.optimizer.OptRuntime.callName(OptRuntime.java:51)
        at rhino.gen.main_js_3._c_anonymous_1(main.js:19)
        at rhino.gen.main_js_3.call(main.js)
        at rhino.optimizer.OptRuntime.call0(OptRuntime.java:15)
        at rhino.gen.main_js_3._c_script_0(main.js:0)
        at rhino.gen.main_js_3.call(main.js)
        at rhino.ContextFactory.doTopCall(ContextFactory.java:346)
        at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3303)
        at rhino.gen.main_js_3.call(main.js)
        at rhino.gen.main_js_3.exec(main.js)
        at rhino.Context.evaluateString(Context.java:1070)
        at mindustry.mod.Scripts.run(Scripts.java:169)
        at mindustry.mod.Scripts.run(Scripts.java:159)
        at mindustry.mod.Mods.lambda$loadScripts$18(Mods.java:440)
        at arc.struct.Seq.each(Seq.java:193)
        at mindustry.mod.Mods.eachEnabled(Mods.java:576)
        at mindustry.mod.Mods.loadScripts(Mods.java:428)
        at mindustry.ClientLauncher.lambda$setup$4(ClientLauncher.java:92)
        at arc.assets.AssetManager$1.loadSync(AssetManager.java:334)
        at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:109)
        at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:74)
        at arc.assets.AssetManager.updateTask(AssetManager.java:591)
        at arc.assets.AssetManager.update(AssetManager.java:440)
        at arc.assets.AssetManager.update(AssetManager.java:465)
        at mindustry.ClientLauncher.update(ClientLauncher.java:137)
        at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
        at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
        at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: arc.util.ArcRuntimeException: File not found: manuals\$rtfm.docs.title\$rtfm.docs.getting-started (internal)
        at arc.files.Fi.read(Fi.java:199)
        at arc.files.Fi.length(Fi.java:868)
        at arc.files.Fi.estimateLength(Fi.java:312)
        at arc.files.Fi.readString(Fi.java:275)
        at arc.files.Fi.readString(Fi.java:266)
        at mindustry.mod.Scripts.readString(Scripts.java:84)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at rhino.MemberBox.invoke(MemberBox.java:105)
        ... 51 more
[E] [rtfm/main.js]: WrappedException: Wrapped arc.util.ArcRuntimeException: File not found: manuals\$rtfm.docs.title\$rtfm.docs.getting-started (internal) (global.js#8)
```

**Comment by DeltaNedas** [comment]
1. does \$ mean file starting with $ or escaped $
2. which bundle, this is fixed for pt_br

**Comment by liuxilu** [comment]
Windows, NTFS, zh-CN bundle

**Comment by DeltaNedas** [comment]
rtfm doesnt have a chinese bundle so youll have to link it.

**Comment by liuxilu** [comment]
It's the game's bundle.

**Comment by DeltaNedas** [comment]
oh no

**Comment by DeltaNedas** [comment]
![Screenshot_15:35:38](https://user-images.githubusercontent.com/39013340/105727473-065a3000-5f23-11eb-9ba4-d6851f5ad0f9.png)
not sure what i did but it should work now for any language (tested in espanol)

**Comment by liuxilu** [comment]
Seems not fixed. And I'd make it clear `external bundle` refers to [this](https://github.com/Anuken/Mindustry/blob/master/TRANSLATING.md#testing-your-translation-bundle).

**Comment by liuxilu** [comment]
https://github.com/Anuken/Mindustry/pull/4439
